Esempio

In [7]:
x = 5 
print(type(x))
x = "ciao"
print(type(x))
x = y = 5
print(type(x), type(y))





<class 'int'>
<class 'str'>
<class 'int'> <class 'int'>


In [11]:
import statistics
data = [1, 2, 3, 4, 5, 6]
x = statistics.mean(data)
print(x)
x = statistics.median(data)
print(x)
x = statistics.stdev(data)
print(x)
x = statistics.pvariance(data)
print(x)
x = statistics.variance(data) #varianza campionaria
print(x)


3.5
3.5
1.8708286933869707
2.9166666666666665
3.5


lezione 22/10/2025

In [ ]:

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(type(a))
print(a.shape) #2 righe, 3 colonne
print(a.ndim) #numero di dimensioni
print(a.size) #numero totale di elementi

print(np.zeros( (3, 4) )) #array di zeri 3 righe, 4 colonne si aspetta un parametro quindi gli passo una tupla
print(np.ones((2, 3, 4), dtype=np.int16)) #array di uno 2, 3, 4

<class 'numpy.ndarray'>
(2, 3)
2
6
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
np.full( (3,5), 13) #valore scelto da te
np.arange(5,10)
np.linspace(0.0,1.0,num = 5) #interpolazione lineare

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

reshape degli array

In [16]:
print( np.arange(1,21) )
np.arange(1,21).reshape(4,5).reshape(10,2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [21]:
m = np.array([1,2,3])
m1 = m*2
b = m*m1 #non è il prodotto riga per colonna
print(b)
print(m)

[ 2  8 18]
[1 2 3]


confronto di array

In [ ]:

m = np.array([3,4,7,8])
t = np.array([3,5,6,8])
s = m >= 7
print(s)
m == t #restutuisce anche esso un array confrontando valore per valore 

[False False  True  True]


array([ True, False, False,  True])

In [ ]:
b = np.array([[4,5,6],[5,6,7]])
m.sum() #built in
b.mean(axis=1) #1 riga  2 colonna


array([5., 6.])

le funzioni universali sono delle funzioni che vanno applicate elemento per elemento

In [ ]:
np.sqrt(b)


[[4 5 6]
 [5 6 7]]


indexing slicing

In [ ]:
b[0,1]
b[0:1] #ottengo un nuovo oggetto che punta alla matrice iniziale

c = np.arange(1, 10).reshape(3, 3)
d = c[:,0]
print(c)

print(id(d))
print(id(c)) #mi dice l'id dell'oggetto cioè se puntano alla stessa cosa
copia = d.view() #punta agli stessi dati
copia1 = d.copy() #crea una copia

print(copia,copia1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
140412818004208
140412818005168
[1 4 7] [1 4 7]


In [ ]:
#reshape restituisce una lista è modo di viusalizzare diverso i dati ma è sempre una lista(vista)
#resize modifica l'array originale
#flatten trasforma una matrice in vettore, copia i dati
#ravel trasforma una matrice in vettore, è una view

Trasposizione: inverte righe e colonne

In [53]:
c.T #matrice trasposta (view)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

pandas

In [60]:
import pandas as pd
serie = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(serie)

serie1 = pd.Series({'a': 1, 'b': 2, 'c': 3})
print(serie1)
print(
serie.dtype,
serie.size,
serie.index,
serie.values    
)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
dtype: int64
int64 5 Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [1 2 3 4 5]


In [61]:
serie.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

dataframe: combinazione di tante serie

In [90]:
df = pd.DataFrame({
    'Nome': ['Lorenzo', 'Mario', 'Luigi'],
    'Eta': [25, 30, 22],
    'Citta': ['Roma' ,'Milano', 'Napoli']
})

df.index = ['a', 'b', 'c']
s = df.loc['a']
f = df.iloc[1]
s.Nome
f.Nome

df.loc['Nome':'Eta', 'a':'b']

df[df.Eta >22]

Nome  Eta   Citta
a  Lorenzo   25    Roma
b    Mario   30  Milano